### Create User

POST http://localhost:8000/api/user/create/
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password",
    "name": "Test User"
}

### LOGIN
POST http://localhost:8000/api/user/token/
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}


### TOKEN
@Token = 03473b3567ff69c1db14520511165f3e934ad9ba
###
# GET TOKEN AT http://localhost:8000/api/user/token/
# USER ME ROUTE

GET http://localhost:8000/api/user/me/
Authorization: token {{Token}}

### UPDATE USER
PATCH  http://localhost:8000/api/user/me/
Content-Type: application/json
Authorization: token {{Token}}

{
   "name": "Wilfred"
}


### Create ingredient
POST http://localhost:8000/api/recipe/ingredients/
Content-Type: application/json
Authorization: token {{Token}}

{
    "name": "Potato"
}

### Create Tag
POST http://localhost:8000/api/recipe/tags/
Content-Type: application/json
Authorization: token {{Token}}

{
    "name": "Delicous"
}
